server:
  port: 2222
spring:
  application:
    name: dubbo-client
dubbo:
  service:
    version: 0.0.1
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  consumer:
    loadbalance: random
embedded:
  zookeeper:
    port: 2181